<?php
/**
 * Created by PhpStorm.
 * User: Darkness
 * Date: 11/30/2016
 * Time: 2:00 PM
 */

namespace common\components;


use yii\db\ActiveQuery;


class FActiveQuery extends ActiveQuery
{
    public function all($db = null)
    {
        //var_dump($this->params); die;
        $items = parent::all($db);
        return FHtml::getTranslatedModels($items);
    }

    public function one($db = null)
    {
        $item = parent::one($db); // TODO: Change the autogenerated stub
        return FHtml::getTranslatedModel($item);
    }
}