/*
Navicat MySQL Data Transfer

Source Server         : mysql
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : moza_business

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2017-06-25 23:59:37
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `object_translation`
-- ----------------------------
DROP TABLE IF EXISTS `object_translation`;
CREATE TABLE `object_translation` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `object_id` bigint(20) DEFAULT NULL,
  `object_type` varchar(100) DEFAULT NULL,
  `lang` varchar(100) DEFAULT NULL,
  `content` text,
  `created_date` datetime DEFAULT NULL,
  `created_user` varchar(100) DEFAULT NULL,
  `application_id` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of object_translation
-- ----------------------------
INSERT INTO `object_translation` VALUES ('12', '28', 'cms_blogs', 'vi', '{\"id\":\"28\",\"thumbnail\":\"\",\"image\":\"\",\"banner\":\"\",\"code\":\"New - 2 - Vi\\u1ec7t nam\",\"name\":\"New 1 - Lahala  - Vi\\u1ec7t nam\",\"overview\":\"New 2 - Hehehe  - Vi\\u1ec7t nam\",\"content\":\"<p>New 3 - Hhahaha<\\/p>\",\"type\":\"\",\"status\":\"\",\"category_id\":\"\",\"is_active\":\"1\",\"lang\":\"\",\"tags\":\"FSDFSD\",\"linkurl\":\"\",\"author\":\"\",\"is_top\":\"0\",\"is_new\":\"0\",\"is_hot\":\"0\",\"count_views\":\"\",\"count_comments\":\"\",\"count_likes\":\"\",\"count_rates\":\"\",\"rates\":\"0\",\"created_date\":\"2017-05-23\",\"created_user\":\"9\",\"modified_date\":\"2017-05-26\",\"modified_user\":\"9\",\"application_id\":\"trayolo\"}', '2017-06-06 20:42:36', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('14', '4', 'cms_service', 'vi', '{\"id\":\"4\",\"thumbnail\":\"\",\"image\":\"\",\"name\":\"Service 1-vi leu leu\",\"overview\":\"Service 1-vi\",\"content\":\"<p>Hahaha ! Ngon vai<\\/p>\",\"linkurl\":\"-en\",\"sort_order\":\"\",\"lang\":\"vi\",\"is_active\":\"1\",\"is_top\":\"1\",\"created_date\":\"2017-06-06\",\"created_user\":\"6\",\"modified_date\":\"2017-06-06 21:18:09\",\"modified_user\":\"6\",\"application_id\":\"trayolo\"}', '2017-06-06 21:18:09', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('17', '2', 'cms_testimonial', 'vi', '{\"id\":\"2\",\"image\":\"cms_testimonial2_image.png\",\"name\":\"Ho Xuan Hung - Viet 3\",\"description\":\"CEO of Projectemplate - VIet 3\",\"location\":\"Hanoi, Vietnam\",\"content\":\"<p>Projectemplate qu&aacute; tuy\\u1ec7t v\\u1eddi Viet 3<\\/p>\",\"rate\":\"3\",\"linkurl\":\"\",\"sort_order\":\"0\",\"is_active\":\"1\",\"is_top\":\"1\",\"created_date\":\"2016-09-25\",\"created_user\":\"6\",\"modified_date\":\"2017-06-06\",\"modified_user\":\"6\",\"application_id\":\"cms\"}', '2017-06-06 22:53:10', '6', 'cms');
INSERT INTO `object_translation` VALUES ('18', '1', 'cms_testimonial', 'vi', '{\"id\":\"1\",\"image\":\"\",\"name\":\"Ho Xuan Cuong VI 3\",\"description\":\"CEO, Founder of Projectemplate\",\"location\":\"Vietnam\",\"content\":\"<p>Projectemplate is very good ! We love their service !<\\/p>\",\"rate\":\"4\",\"linkurl\":\"\",\"sort_order\":\"1\",\"is_active\":\"1\",\"is_top\":\"1\",\"created_date\":\"2016-09-25\",\"created_user\":\"6\",\"modified_date\":\"2016-09-26\",\"modified_user\":\"6\",\"application_id\":\"cms\"}', '2017-06-06 22:58:17', '6', 'cms');
INSERT INTO `object_translation` VALUES ('19', '31', 'cms_blogs', 'vi', '{\"id\":\"31\",\"thumbnail\":\"\",\"image\":\"\",\"banner\":\"\",\"code\":\"New Blogs VI\",\"name\":\"New Blogs - Description VI\",\"overview\":\"Hahah 1 2 3 4 5 6\",\"content\":\"<p>444<\\/p>\",\"type\":\"\",\"status\":\"\",\"category_id\":\"\",\"is_active\":\"0\",\"lang\":\"\",\"tags\":\"\",\"linkurl\":\"\",\"author\":\"\",\"is_top\":\"0\",\"is_new\":\"0\",\"is_hot\":\"0\",\"count_views\":\"\",\"count_comments\":\"\",\"count_likes\":\"\",\"count_rates\":\"\",\"rates\":\"0\",\"created_date\":\"2017-06-02\",\"created_user\":\"6\",\"modified_date\":\"2017-06-02\",\"modified_user\":\"6\",\"application_id\":\"trayolo\"}', '2017-06-06 23:37:50', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('20', '30', 'cms_blogs', 'vi', '{\"id\":\"30\",\"thumbnail\":\"\",\"image\":\"\",\"banner\":\"\",\"code\":\"Lalalala - VI 2\",\"name\":\"HIHIHi - New VI 3\",\"overview\":\"HOH\\u00d4HOHO - New 3\",\"content\":\"<p>Hehehe&nbsp;- New FDS<\\/p>\",\"type\":\"\",\"status\":\"\",\"category_id\":\"\",\"is_active\":\"0\",\"lang\":\"\",\"tags\":\"\",\"linkurl\":\"\",\"author\":\"\",\"is_top\":\"0\",\"is_new\":\"0\",\"is_hot\":\"0\",\"count_views\":\"\",\"count_comments\":\"\",\"count_likes\":\"\",\"count_rates\":\"\",\"rates\":\"0\",\"created_date\":\"2017-06-02\",\"created_user\":\"6\",\"modified_date\":\"2017-06-02\",\"modified_user\":\"6\",\"application_id\":\"trayolo\"}', '2017-06-06 23:48:51', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('21', '29', 'cms_blogs', 'vi', '{\"id\":\"29\",\"thumbnail\":\"\",\"image\":\"\",\"banner\":\"\",\"code\":\"Test Viet\",\"name\":\"Test Create new - Viet\",\"overview\":\"Vietnam\",\"content\":\"\",\"type\":\"\",\"status\":\"\",\"category_id\":\"\",\"is_active\":\"0\",\"lang\":\"\",\"tags\":\"\",\"linkurl\":\"\",\"author\":\"\",\"is_top\":\"0\",\"is_new\":\"0\",\"is_hot\":\"0\",\"count_views\":\"\",\"count_comments\":\"\",\"count_likes\":\"\",\"count_rates\":\"\",\"rates\":\"0\",\"created_date\":\"2017-06-02\",\"created_user\":\"6\",\"modified_date\":\"2017-06-06 23:51:49\",\"modified_user\":\"6\",\"application_id\":\"trayolo\"}', '2017-06-06 23:51:49', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('22', '4', 'application', 'vi', '{\"id\":\"4\",\"logo\":\"trayolo_application4_logo.png\",\"code\":\"trayolo\",\"name\":\"Travel Trip Planner\",\"description\":\"\",\"keywords\":\"\",\"note\":\"\",\"lang\":\"vi\",\"modules\":\"\",\"storage_max\":\"\",\"storage_current\":\"\",\"address\":\"\",\"map\":\"\",\"website\":\"www.trayolo.com\",\"email\":\"support@trayolo.com\",\"phone\":\"\",\"fax\":\"\",\"chat\":\"\",\"facebook\":\"\",\"twitter\":\"\",\"google\":\"\",\"youtube\":\"\",\"copyright\":\"Copyright by\",\"terms_of_service\":\"\",\"profile\":\"\",\"privacy_policy\":\"\",\"is_active\":\"1\",\"type\":\"\",\"status\":\"\",\"page_size\":\"\",\"main_color\":\"\",\"cache_enabled\":\"\",\"currency_format\":\"\",\"date_format\":\"\",\"web_theme\":\"\",\"admin_form_alignment\":\"\",\"body_css\":\"\",\"body_style\":\"\",\"page_css\":\"\",\"page_style\":\"\",\"owner_id\":\"\",\"created_date\":\"2017-05-08 11:07:32\",\"created_user\":\"6\",\"modified_date\":\"2017-05-08 11:42:37\",\"modified_user\":\"6\"}', '2017-06-07 00:02:22', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('23', null, 'cms_article', 'vi', '{\"id\":null,\"thumbnail\":\"\",\"image\":\"\",\"banner\":\"\",\"code\":\"fdsafsad\",\"name\":\"fsdafasdfsadfd\",\"overview\":\"fdsfsdfdsaf\",\"content\":\"\",\"linkurl\":\"\",\"sort_order\":\"\",\"type\":\"\",\"lang\":\"\",\"is_active\":\"1\",\"is_top\":\"\",\"created_date\":\"2017-06-10 05:06:04\",\"created_user\":6,\"modified_date\":\"\",\"modified_user\":\"\",\"application_id\":\"trayolo\"}', '2017-06-10 05:06:04', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('24', '33', 'cms_blogs', 'vi', '{\"id\":\"33\",\"thumbnail\":\"\",\"image\":\"\",\"banner\":\"\",\"code\":\"Test EN NEW\",\"name\":\"Haha VI\",\"overview\":\"hihi VI\",\"content\":\"<p>SDFDFDSF<\\/p>\",\"type\":\"\",\"status\":\"\",\"category_id\":\"\",\"is_active\":\"0\",\"lang\":\"\",\"tags\":\"FSFSDFSD\",\"linkurl\":\"\",\"author\":\"\",\"is_top\":\"0\",\"is_new\":\"0\",\"is_hot\":\"0\",\"count_views\":\"\",\"count_comments\":\"\",\"count_likes\":\"\",\"count_rates\":\"\",\"rates\":\"0\",\"created_date\":\"2017-06-09\",\"created_user\":\"6\",\"modified_date\":\"2017-06-10 06:38:12\",\"modified_user\":\"6\",\"application_id\":\"trayolo\"}', '2017-06-10 06:38:12', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('25', '32', 'cms_blogs', 'vi', '{\"id\":\"32\",\"thumbnail\":\"\",\"image\":\"\",\"banner\":\"\",\"code\":\"Test EN NEW\",\"name\":\"Haha fds\",\"overview\":\"hihi\",\"content\":\"<p>SDFDFDSF<\\/p>\",\"type\":\"\",\"status\":\"\",\"category_id\":\"\",\"is_active\":\"0\",\"lang\":\"\",\"tags\":\"FSFSDFSD\",\"linkurl\":\"\",\"author\":\"\",\"is_top\":\"0\",\"is_new\":\"0\",\"is_hot\":\"0\",\"count_views\":\"\",\"count_comments\":\"\",\"count_likes\":\"\",\"count_rates\":\"\",\"rates\":\"0\",\"created_date\":\"2017-06-09\",\"created_user\":\"6\",\"modified_date\":\"2017-06-10 06:38:21\",\"modified_user\":6,\"application_id\":\"trayolo\"}', '2017-06-10 06:38:21', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('26', '34', 'cms_blogs', 'vi', '{\"id\":\"34\",\"thumbnail\":\"\",\"image\":\"\",\"banner\":\"\",\"code\":\"TEST NEW 2\",\"name\":\"TEST NEW 2 VI\",\"overview\":\"TEST NEW 2\",\"content\":\"\",\"type\":\"\",\"status\":\"\",\"category_id\":\"\",\"is_active\":\"0\",\"lang\":\"\",\"tags\":\"\",\"linkurl\":\"\",\"author\":\"\",\"is_top\":\"0\",\"is_new\":\"0\",\"is_hot\":\"0\",\"count_views\":\"\",\"count_comments\":\"\",\"count_likes\":\"\",\"count_rates\":\"\",\"rates\":\"0\",\"created_date\":\"2017-06-09\",\"created_user\":\"6\",\"modified_date\":\"2017-06-10 11:43:33\",\"modified_user\":6,\"application_id\":\"trayolo\"}', '2017-06-10 08:54:55', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('27', '35', 'cms_blogs', 'vi', '{\"id\":\"35\",\"thumbnail\":\"\",\"image\":\"\",\"banner\":\"\",\"code\":\"TEST NEW 3\",\"name\":\"TEST NEW 3 VI\",\"overview\":\"TEST NEW 3\",\"content\":\"\",\"type\":\"\",\"status\":\"\",\"category_id\":\"\",\"is_active\":\"1\",\"lang\":\"\",\"tags\":\"\",\"linkurl\":\"\",\"author\":\"\",\"is_top\":\"0\",\"is_new\":\"0\",\"is_hot\":\"0\",\"count_views\":\"\",\"count_comments\":\"\",\"count_likes\":\"\",\"count_rates\":\"\",\"rates\":\"0\",\"created_date\":\"2017-06-09\",\"created_user\":\"6\",\"modified_date\":\"2017-06-10 09:05:25\",\"modified_user\":\"6\",\"application_id\":\"trayolo\"}', '2017-06-10 09:05:25', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('31', '156', 'object_setting', 'vi', '{\"id\":156,\"object_type\":\"common\",\"meta_key\":\"cms_blogs.type\",\"key\":\"lala\",\"value\":\"vai - vi\",\"description\":null,\"icon\":null,\"color\":null,\"is_active\":1,\"sort_order\":0,\"application_id\":\"trayolo\"}', '2017-06-10 11:47:36', '6', 'trayolo');
INSERT INTO `object_translation` VALUES ('32', '27', 'object_category', 'vi', '{\"id\":\"27\",\"parent_id\":\"\",\"image\":\"\",\"name\":\"sdfadsfasd - vn\",\"description\":\"\",\"sort_order\":\"\",\"is_active\":\"1\",\"is_top\":\"\",\"is_hot\":\"\",\"object_type\":\"\",\"created_date\":\"2017-06-09 19:20:02\",\"modified_date\":\"2017-06-10 12:33:45\",\"application_id\":\"trayolo\"}', '2017-06-10 12:34:43', '6', 'trayolo');
